name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: [ '8.0.x' ]  # Can easily be expanded for other versions

    steps:
      # Step 1: Check out the repository
      - uses: actions/checkout@v4

      # Step 2: Set up the .NET SDK with matrix version
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: List Files within ElProjectGrande sln
        run: cd ElProjectGrande && ls

      # Step 3: Restore dependencies for the entire solution
      - name: Restore Dependencies
        run: dotnet restore ./BackendServer/BackendServer.sln

      # Step 4: Build the backend project in Debug mode
      - name: Build Backend Project
        run: dotnet build ./Backend/BackendServer/BackendServer.csproj --configuration Debug

      # Step 5: Run Tests from the test project
      - name: Run Tests
        run: dotnet test ./Backend/BackendTest/BackendTest.csproj --configuration Debug --verbosity normal
